// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (client_id, merchant_id, phone_number, status)
VALUES ($1, $2, $3, $4)
RETURNING id, client_id, merchant_id, phone_number, status, created_at, updated_at
`

type CreateCustomerParams struct {
	ClientID    uuid.UUID      `json:"client_id"`
	MerchantID  uuid.UUID      `json:"merchant_id"`
	PhoneNumber string         `json:"phone_number"`
	Status      CustomerStatus `json:"status"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ClientID,
		arg.MerchantID,
		arg.PhoneNumber,
		arg.Status,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.MerchantID,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByClientAndMerchantAndPhone = `-- name: GetCustomerByClientAndMerchantAndPhone :one
SELECT id, client_id, merchant_id, phone_number, status, created_at, updated_at FROM customers
WHERE client_id = $1 AND merchant_id = $2 AND phone_number = $3
`

type GetCustomerByClientAndMerchantAndPhoneParams struct {
	ClientID    uuid.UUID `json:"client_id"`
	MerchantID  uuid.UUID `json:"merchant_id"`
	PhoneNumber string    `json:"phone_number"`
}

func (q *Queries) GetCustomerByClientAndMerchantAndPhone(ctx context.Context, arg GetCustomerByClientAndMerchantAndPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByClientAndMerchantAndPhone, arg.ClientID, arg.MerchantID, arg.PhoneNumber)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.MerchantID,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, client_id, merchant_id, phone_number, status, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.MerchantID,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomersByClient = `-- name: ListCustomersByClient :many
SELECT id, client_id, merchant_id, phone_number, status, created_at, updated_at FROM customers
WHERE client_id = $1
ORDER BY created_at
`

func (q *Queries) ListCustomersByClient(ctx context.Context, clientID uuid.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.MerchantID,
			&i.PhoneNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByMerchant = `-- name: ListCustomersByMerchant :many
SELECT id, client_id, merchant_id, phone_number, status, created_at, updated_at FROM customers
WHERE merchant_id = $1
ORDER BY created_at
`

func (q *Queries) ListCustomersByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.MerchantID,
			&i.PhoneNumber,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :one
UPDATE customers
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, merchant_id, phone_number, status, created_at, updated_at
`

type UpdateCustomerStatusParams struct {
	ID     uuid.UUID      `json:"id"`
	Status CustomerStatus `json:"status"`
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerStatus, arg.ID, arg.Status)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.MerchantID,
		&i.PhoneNumber,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
