// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clientExistsByID = `-- name: ClientExistsByID :one
SELECT EXISTS(
    SELECT 1 FROM clients WHERE id = $1
)
`

func (q *Queries) ClientExistsByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, clientExistsByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
`

func (q *Queries) CountClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (client_name, status)
VALUES ($1, $2)
RETURNING id, client_name, status, created_at, updated_at
`

type CreateClientParams struct {
	ClientName string       `json:"client_name"`
	Status     ClientStatus `json:"status"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.ClientName, arg.Status)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :execrows
DELETE FROM clients WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteClient, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, client_name, status, created_at, updated_at
FROM clients
WHERE id = $1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClientByName = `-- name: GetClientByName :one
SELECT id, client_name, status, created_at, updated_at
FROM clients
WHERE client_name = $1
`

func (q *Queries) GetClientByName(ctx context.Context, clientName string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByName, clientName)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveClients = `-- name: ListActiveClients :many
SELECT id, client_name, status, created_at, updated_at
FROM clients
WHERE status = 'ACTIVE'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveClientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveClients(ctx context.Context, arg ListActiveClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listActiveClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClients = `-- name: ListClients :many
SELECT id, client_name, status, created_at, updated_at
FROM clients
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListClientsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.ClientName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientStatus = `-- name: UpdateClientStatus :one
UPDATE clients
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_name, status, created_at, updated_at
`

type UpdateClientStatusParams struct {
	ID     uuid.UUID    `json:"id"`
	Status ClientStatus `json:"status"`
}

func (q *Queries) UpdateClientStatus(ctx context.Context, arg UpdateClientStatusParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClientStatus, arg.ID, arg.Status)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
