// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: deposits.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO deposits (amount, currency, payer_type, payer_phone_number, payer_provider, client_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, amount, currency, payer_type, payer_phone_number, payer_provider, client_id, created_at, updated_at
`

type CreateDepositParams struct {
	Amount           pgtype.Numeric  `json:"amount"`
	Currency         string          `json:"currency"`
	PayerType        PayerType       `json:"payer_type"`
	PayerPhoneNumber string          `json:"payer_phone_number"`
	PayerProvider    PaymentProvider `json:"payer_provider"`
	ClientID         uuid.UUID       `json:"client_id"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, createDeposit,
		arg.Amount,
		arg.Currency,
		arg.PayerType,
		arg.PayerPhoneNumber,
		arg.PayerProvider,
		arg.ClientID,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.PayerType,
		&i.PayerPhoneNumber,
		&i.PayerProvider,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByID = `-- name: GetDepositByID :one
SELECT id, amount, currency, payer_type, payer_phone_number, payer_provider, client_id, created_at, updated_at FROM deposits WHERE id = $1
`

func (q *Queries) GetDepositByID(ctx context.Context, id uuid.UUID) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByID, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.PayerType,
		&i.PayerPhoneNumber,
		&i.PayerProvider,
		&i.ClientID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
