// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PayerType string

const (
	PayerTypeMMO PayerType = "MMO"
)

func (e *PayerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayerType(s)
	case string:
		*e = PayerType(s)
	default:
		return fmt.Errorf("unsupported scan type for PayerType: %T", src)
	}
	return nil
}

type NullPayerType struct {
	PayerType PayerType `json:"payer_type"`
	Valid     bool      `json:"valid"` // Valid is true if PayerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayerType) Scan(value interface{}) error {
	if value == nil {
		ns.PayerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayerType), nil
}

type PaymentProvider string

const (
	PaymentProviderMTNMOMOCMR PaymentProvider = "MTN_MOMO_CMR"
	PaymentProviderORANGECMR  PaymentProvider = "ORANGE_CMR"
)

func (e *PaymentProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProvider(s)
	case string:
		*e = PaymentProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProvider: %T", src)
	}
	return nil
}

type NullPaymentProvider struct {
	PaymentProvider PaymentProvider `json:"payment_provider"`
	Valid           bool            `json:"valid"` // Valid is true if PaymentProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProvider), nil
}

type Client struct {
	ID          uuid.UUID `json:"id"`
	ClientName  string    `json:"client_name"`
	Email       string    `json:"email"`
	PhoneNumber string    `json:"phone_number"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Deposit struct {
	ID               uuid.UUID       `json:"id"`
	Amount           pgtype.Numeric  `json:"amount"`
	Currency         string          `json:"currency"`
	PayerType        PayerType       `json:"payer_type"`
	PayerPhoneNumber string          `json:"payer_phone_number"`
	PayerProvider    PaymentProvider `json:"payer_provider"`
	ClientID         uuid.UUID       `json:"client_id"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}
