// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	GetClientByID(ctx context.Context, id uuid.UUID) (Client, error)
	GetDepositByID(ctx context.Context, id uuid.UUID) (Deposit, error)
}

var _ Querier = (*Queries)(nil)
