// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: integrations.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integrations (provider, location_id, access_token, refresh_token, token_expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, provider, location_id, access_token, refresh_token, token_expires_at, created_at, updated_at
`

type CreateIntegrationParams struct {
	Provider       string    `json:"provider"`
	LocationID     string    `json:"location_id"`
	AccessToken    string    `json:"access_token"`
	RefreshToken   string    `json:"refresh_token"`
	TokenExpiresAt time.Time `json:"token_expires_at"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.Provider,
		arg.LocationID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.LocationID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIntegration = `-- name: DeleteIntegration :execrows
DELETE FROM integrations WHERE id = $1
`

func (q *Queries) DeleteIntegration(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntegration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, provider, location_id, access_token, refresh_token, token_expires_at, created_at, updated_at FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id uuid.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.LocationID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
