// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Integration struct {
	ID             uuid.UUID `json:"id"`
	Provider       string    `json:"provider"`
	LocationID     string    `json:"location_id"`
	AccessToken    string    `json:"access_token"`
	RefreshToken   string    `json:"refresh_token"`
	TokenExpiresAt time.Time `json:"token_expires_at"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type WebhookEvent struct {
	ID        uuid.UUID `json:"id"`
	Provider  string    `json:"provider"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
	Processed bool      `json:"processed"`
	CreatedAt time.Time `json:"created_at"`
}
