// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error)
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error)
	DeleteIntegration(ctx context.Context, id uuid.UUID) (int64, error)
	GetIntegrationByID(ctx context.Context, id uuid.UUID) (Integration, error)
	GetWebhookEventByID(ctx context.Context, id uuid.UUID) (WebhookEvent, error)
}

var _ Querier = (*Queries)(nil)
