// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: webhook_events.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one
INSERT INTO webhook_events (provider, event_type, payload, processed)
VALUES ($1, $2, $3, $4)
RETURNING id, provider, event_type, payload, processed, created_at
`

type CreateWebhookEventParams struct {
	Provider  string `json:"provider"`
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
	Processed bool   `json:"processed"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.Provider,
		arg.EventType,
		arg.Payload,
		arg.Processed,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookEventByID = `-- name: GetWebhookEventByID :one
SELECT id, provider, event_type, payload, processed, created_at FROM webhook_events WHERE id = $1
`

func (q *Queries) GetWebhookEventByID(ctx context.Context, id uuid.UUID) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByID, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.CreatedAt,
	)
	return i, err
}
